// Copyright 2026 kropath Authors.
// SPDX-License-Identifier: Apache-2.0

// gen-features writes docs/features.yaml from the canonical features.All registry.
//
// Usage:
//
//	go run ./cmd/gen-features           # regenerate docs/features.yaml
//	go run ./cmd/gen-features --check   # exit non-zero if the file is stale
//
// Run via `make features-gen` or `make features-verify`.
// Must be run from the repository root.
package main

import (
	"bytes"
	"fmt"
	"io"
	"os"

	"gopkg.in/yaml.v3"

	"github.com/kropath/kropath-controller/internal/features"
)

const outPath = "docs/features.yaml"

// generate marshals reconcilers to YAML and writes the result (with header) to w.
func generate(w io.Writer, reconcilers []features.Reconciler) error {
	doc, err := yaml.Marshal(struct {
		Reconcilers []features.Reconciler `yaml:"reconcilers"`
	}{Reconcilers: reconcilers})
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if _, err := fmt.Fprintln(w, "# Auto-generated by cmd/gen-features — do NOT edit by hand."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "# Regenerate with: make features-gen"); err != nil {
		return err
	}
	_, err = w.Write(doc)
	return err
}

func main() {
	checkMode := len(os.Args) > 1 && os.Args[1] == "--check"

	var buf bytes.Buffer
	if err := generate(&buf, features.All); err != nil {
		fmt.Fprintf(os.Stderr, "gen-features: %v\n", err)
		os.Exit(1)
	}

	if checkMode {
		existing, err := os.ReadFile(outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "features-verify: cannot read %s: %v\n", outPath, err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, buf.Bytes()) {
			fmt.Fprintf(os.Stderr, "features-verify: %s is stale — run: make features-gen\n", outPath)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "features-verify: %s is up to date\n", outPath)
		return
	}

	if err := os.WriteFile(outPath, buf.Bytes(), 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "gen-features: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen-features: wrote %s (%d reconcilers)\n", outPath, len(features.All))
}
