// Copyright 2026 kropath Authors.
// SPDX-License-Identifier: Apache-2.0

// gen-features writes docs/features.yaml from the canonical features.All registry.
//
// Usage:
//
//	go run ./cmd/gen-features           # regenerate docs/features.yaml
//	go run ./cmd/gen-features --check   # exit non-zero if the file is stale
//
// Run via `make generate-features` or `make check-features`.
// Must be run from the repository root.
package main

import (
	"bytes"
	"fmt"
	"os"

	"gopkg.in/yaml.v3"

	"github.com/kropath/kropath-controller/internal/features"
)

const outPath = "docs/features.yaml"

func main() {
	checkMode := len(os.Args) > 1 && os.Args[1] == "--check"

	// Marshal the registry rather than hand-writing fields, so a field added to
	// features.Reconciler appears here automatically. Hand-writing would let
	// docs/features.yaml drift into the stale parallel artifact this generator
	// exists to prevent.
	doc, err := yaml.Marshal(struct {
		Reconcilers []features.Reconciler `yaml:"reconcilers"`
	}{Reconcilers: features.All})
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-features: marshal: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Auto-generated by cmd/gen-features — do NOT edit by hand.")
	fmt.Fprintln(&buf, "# Regenerate with: make generate-features")
	buf.Write(doc)

	if checkMode {
		existing, err := os.ReadFile(outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "check-features: cannot read %s: %v\n", outPath, err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, buf.Bytes()) {
			fmt.Fprintf(os.Stderr, "check-features: %s is stale — run: make generate-features\n", outPath)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "check-features: %s is up to date\n", outPath)
		return
	}

	if err := os.WriteFile(outPath, buf.Bytes(), 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "gen-features: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen-features: wrote %s (%d reconcilers)\n", outPath, len(features.All))
}
