// Copyright 2026 kropath Authors.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bytes"
	"strings"
	"testing"

	"github.com/kropath/kropath-controller/internal/features"
)

// TestGenerate_empty verifies that an empty registry still produces a valid
// YAML document with the required header and an explicit empty reconcilers list.
func TestGenerate_empty(t *testing.T) {
	var buf bytes.Buffer
	if err := generate(&buf, nil); err != nil {
		t.Fatalf("generate(nil): %v", err)
	}
	out := buf.String()
	if !strings.HasPrefix(out, "# Auto-generated by cmd/gen-features") {
		t.Errorf("missing 'do not edit' header: %q", out)
	}
	if !strings.Contains(out, "# Regenerate with: make features-gen") {
		t.Errorf("missing 'make features-gen' instruction: %q", out)
	}
	if !strings.Contains(out, "reconcilers: []") {
		t.Errorf("expected empty reconcilers list, got:\n%s", out)
	}
}

// TestGenerate_multiFeature verifies that a non-empty registry produces YAML
// that contains each reconciler's Name, Package, and Stability fields.
func TestGenerate_multiFeature(t *testing.T) {
	reconcilers := []features.Reconciler{
		{
			Name:         "FooConfig",
			Package:      "fooconfig",
			Description:  "Reconciles FooConfig CRs.",
			Kinds:        []string{"FooConfig", "KropathConfig"},
			SinceVersion: "v0.1.0",
			Stability:    "alpha",
		},
		{
			Name:         "BarConfig",
			Package:      "barconfig",
			Description:  "Reconciles BarConfig CRs.",
			Kinds:        []string{"BarConfig", "KropathConfig"},
			SinceVersion: "v0.2.0",
			Stability:    "stable",
		},
	}

	var buf bytes.Buffer
	if err := generate(&buf, reconcilers); err != nil {
		t.Fatalf("generate: %v", err)
	}
	out := buf.String()

	for _, want := range []string{
		"name: FooConfig",
		"package: fooconfig",
		"stability: alpha",
		"name: BarConfig",
		"package: barconfig",
		"stability: stable",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q:\n%s", want, out)
		}
	}
}

// TestGenerate_deterministic verifies that calling generate twice with the same
// input produces byte-identical output — no map-iteration nondeterminism.
func TestGenerate_deterministic(t *testing.T) {
	var first, second bytes.Buffer
	if err := generate(&first, features.All); err != nil {
		t.Fatalf("first generate: %v", err)
	}
	if err := generate(&second, features.All); err != nil {
		t.Fatalf("second generate: %v", err)
	}
	if !bytes.Equal(first.Bytes(), second.Bytes()) {
		t.Error("generate is not deterministic: two calls with the same input produced different output")
	}
}

// TestGenerate_allFeatures verifies that the output contains an entry for every
// reconciler in features.All, confirming the live registry is fully marshalled.
func TestGenerate_allFeatures(t *testing.T) {
	var buf bytes.Buffer
	if err := generate(&buf, features.All); err != nil {
		t.Fatalf("generate: %v", err)
	}
	out := buf.String()
	for _, r := range features.All {
		if !strings.Contains(out, "name: "+r.Name) {
			t.Errorf("output missing reconciler %q", r.Name)
		}
	}
}
