// Copyright 2026 kropath Authors.
// SPDX-License-Identifier: Apache-2.0

// gen-features writes docs/features.yaml from the canonical features.All registry.
//
// Usage:
//
//	go run ./cmd/gen-features           # regenerate docs/features.yaml
//	go run ./cmd/gen-features --check   # exit non-zero if the file is stale
//
// Run via `make generate-features` or `make check-features`.
// Must be run from the repository root.
package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/kropath/kropath-controller/internal/features"
)

const outPath = "docs/features.yaml"

func main() {
	checkMode := len(os.Args) > 1 && os.Args[1] == "--check"

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Auto-generated by cmd/gen-features — do NOT edit by hand.")
	fmt.Fprintln(&buf, "# Regenerate with: make generate-features")
	fmt.Fprintln(&buf, "reconcilers:")
	for _, r := range features.All {
		fmt.Fprintf(&buf, "  - name: %s\n    package: %s\n", r.Name, r.Package)
	}

	if checkMode {
		existing, err := os.ReadFile(outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "check-features: cannot read %s: %v\n", outPath, err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, buf.Bytes()) {
			fmt.Fprintf(os.Stderr, "check-features: %s is stale — run: make generate-features\n", outPath)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "check-features: %s is up to date\n", outPath)
		return
	}

	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-features: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen-features: wrote %s (%d reconcilers)\n", outPath, len(features.All))
}
